Repository Project-AllForOne/Front, pull requests merged in 2025-02, with the labels that each got.

#85 향 테라피 화면 구현 완료 - Feature/perfume therapy
  src/App.js
  src/components/footer/Footer.js
  src/components/sidebar/Sidebar.js
  src/components/therapy/TherapyButton.js
  src/components/therapy/TherapyCategories.js
  src/components/therapy/TherapyDiffuserRecommend.js
  src/components/therapy/TherapyKeywordDescription.js
  src/components/therapy/TherapyKeywordSelector.js
  src/components/therapy/TherapyMain.js
  src/css/therapy/TherapyButton.module.css
  src/css/therapy/TherapyCategories.module.css
  src/css/therapy/TherapyDiffuserRecommend.module.css
  src/css/therapy/TherapyKeywordDescription.module.css
  src/css/therapy/TherapyKeywordSelector.module.css
  src/css/therapy/TherapyMain.module.css
  src/data/DiffuserData.js
  src/pages/therapy/Therapy.js
Labels: merge

#86 향료/ 향수 컴포넌트 분리 - Fix/booklist fix
  public/images/default-spice.png
  public/images/loading.gif
  src/components/chat/input/ChatInput.js
  src/components/chat/input/ImageUpload.js
  src/components/chat/layout/ChatContainer.js
  src/components/chat/layout/ChatHeader.js
  src/components/chat/messages/LoadingDots.js
  src/components/chat/messages/MessageItem.js
  src/components/chat/messages/MessageList.js
  src/components/chat/modals/ImageModal.js
  src/components/chat/modals/LoginModal.js
  src/components/chat/search/SearchBar.js
  src/components/perfumes/Pagination.js
  src/components/perfumes/PerfumeCard.js
  src/components/perfumes/PerfumeFilters.js
  src/components/perfumes/PerfumeModal.js
  src/components/spices/Pagination.js
  src/components/spices/SpicesCard.js
  src/components/spices/SpicesFilters.js
  src/components/spices/SpicesModal.js
  src/css/SpicesList.css
  src/css/chat/ChatContainer.module.css
  src/css/chat/ChatHeader.module.css
  src/css/chat/ChatInput.module.css
  src/css/chat/Loading.module.css
  src/css/chat/MessageItem.module.css
  src/css/chat/MessageList.module.css
  src/css/chat/Modal.module.css
  src/css/chat/SearchBar.module.css
  src/css/perfumes/PerfumeCard.module.css
  src/css/perfumes/PerfumeFilters.module.css
  src/css/perfumes/PerfumeList.module.css
  src/css/perfumes/PerfumeModal.module.css
  src/css/perfumes/PerfumePagination.module.css
  src/css/spices/SpicesCard.module.css
  src/css/spices/SpicesFilters.module.css
  src/css/spices/SpicesList.module.css
  src/css/spices/SpicesModal.module.css
  src/css/spices/SpicesPagination.module.css
  src/data/line_.json
  src/pages/booklist/PerfumeList.js
  src/pages/booklist/SpicesList.js
  src/pages/booklist/hooks/usePerfumeState.js
  src/pages/booklist/hooks/useSpicesState.js
  src/pages/chat/ChatLogic.js
Labels: merge

#88 향수 상세 페이지 화면 구현 Feature/perfume detail
  src/App.js
  src/components/perfumes/PerfumeDetail.js
  src/components/perfumes/PerfumeReviews.js
  src/components/perfumes/ReviewSlider.js
  src/components/perfumes/SimilarPerfumes.js
  src/components/therapy/TherapyCategories.js
  src/components/therapy/TherapyDiffuserRecommend.js
  src/components/therapy/TherapyKeywordDescription.js
  src/components/therapy/TherapyKeywordSelector.js
  src/components/therapy/TherapyMain.js
  src/css/components/Footer.css
  src/css/perfumes/PerfumeDetail.module.css
  src/css/perfumes/PerfumeReviews.module.css
  src/css/perfumes/ReviewSlider.module.css
  src/css/perfumes/SimilarPerfumes.module.css
  src/css/therapy/TherapyCategories.module.css
  src/css/therapy/TherapyDiffuserRecommend.module.css
  src/css/therapy/TherapyKeywordDescription.module.css
  src/css/therapy/TherapyKeywordSelector.module.css
  src/css/therapy/TherapyMain.module.css
  src/data/DiffuserData.js
  src/data/NoteData.js
  src/data/PerfumeData.js
  src/pages/therapy/Therapy.js
Labels: merge

#91 향 테라피 연동 Feature/therapy api
  public/images/perfume.png
  src/Store.js
  src/api/TherapyAPICalls.js
  src/components/loading/ColorLoadingScreen.js
  src/components/therapy/TherapyCategories.js
  src/components/therapy/TherapyDiffuserRecommend.js
  src/css/components/ColorLoadingScreen.module.css
  src/css/therapy/TherapyDiffuserRecommend.module.css
  src/data/DiffuserData.js
  src/module/TherapyModule.js
Labels: merge

#92 메인 페이지의 관리자 대시보드 모달 작성 - feature/admin-dashboard
  package-lock.json
  package.json
  src/css/Main.css
  src/css/admin/DashboardModal.css
  src/pages/Main.js
  src/pages/admin/AdminMembers.js
  src/pages/admin/ChartComponent.js
  src/pages/admin/DashboardModal.js
Labels: RFM, merge

#94 Fix/admin dashboard color edit
  src/css/admin/DashboardModal.css
  src/pages/admin/DashboardModal.js
Labels: merge

#95 Fix/perfume list refactoring
  src/api/PerfumeAPICalls.js
  src/components/perfumes/Pagination.js
  src/components/perfumes/PerfumeCard.js
  src/components/perfumes/PerfumeDetail.js
  src/components/perfumes/PerfumeReviews.js
  src/components/spices/Pagination.js
  src/components/spices/SpicesCard.js
  src/components/spices/SpicesModal.js
  src/css/perfumes/PerfumeCard.module.css
  src/css/perfumes/PerfumeDetail.module.css
  src/css/perfumes/PerfumePagination.module.css
  src/css/spices/SpicesCard.module.css
  src/css/spices/SpicesList.module.css
  src/css/spices/SpicesModal.module.css
  src/pages/booklist/PerfumeList.js
  src/pages/booklist/SpicesList.js
  src/pages/booklist/hooks/usePerfumeState.js
  src/pages/booklist/hooks/useSpicesState.js
Labels: in progress, merge

#98 향료 모달 재연동
  src/components/perfumes/PerfumeCard.js
  src/components/perfumes/PerfumeDetail.js
  src/components/spices/SpicesCard.js
  src/components/spices/SpicesModal.js
  src/css/spices/SpicesCard.module.css
  src/css/spices/SpicesList.module.css
  src/pages/booklist/PerfumeList.js
  src/pages/booklist/SpicesList.js
  src/pages/booklist/hooks/usePerfumeState.js
  src/pages/booklist/hooks/useSpicesState.js
Labels: merge

#99 [Fix] edit perfume list
  src/api/PerfumeAPICalls.js
  src/components/perfumes/PerfumeCard.js
  src/components/perfumes/PerfumeFilters.js
  src/components/perfumes/PerfumeModal.js
  src/css/perfumes/PerfumeCard.module.css
  src/css/perfumes/PerfumeModal.module.css
  src/pages/booklist/PerfumeList.js
  src/pages/booklist/hooks/usePerfumeState.js
Labels: RFM, merge

#102 향수 상세 페이지 연동 Feature/perfume review
  src/App.js
  src/Store.js
  src/api/Apis.js
  src/api/PerfumeAPICalls.js
  src/api/ReviewAPICalls.js
  src/components/perfumes/PerfumeCard.js
  src/components/perfumes/PerfumeDetail.js
  src/components/perfumes/PerfumeReviews.js
  src/components/perfumes/ReviewModal.js
  src/components/perfumes/ReviewSlider.js
  src/components/perfumes/SimilarPerfumes.js
  src/css/perfumes/PerfumeDetail.module.css
  src/css/perfumes/PerfumeReviews.module.css
  src/css/perfumes/ReviewModal.module.css
  src/css/perfumes/ReviewSlider.module.css
  src/css/perfumes/SimilarPerfumes.module.css
  src/module/PerfumeModule.js
  src/module/ReviewModule.js
  src/pages/booklist/PerfumeList.js
Labels: merge

#107 향수 북마크 Feature/perfume like
  src/App.js
  src/Store.js
  src/api/BookmarkAPICalls.js
  src/components/perfumes/BookmarkPopover.js
  src/components/perfumes/PerfumeCard.js
  src/components/perfumes/PerfumeFilters.js
  src/css/perfumes/BookmarkPopover.module.css
  src/css/perfumes/PerfumeCard.module.css
  src/css/perfumes/PerfumeFilters.module.css
  src/module/BookmarkModule.js
  src/pages/booklist/PerfumeList.js
  src/pages/booklist/hooks/usePerfumeState.js
Labels: merge

#109 [FEAT] 리뷰 수정 삭제
  src/api/ReviewAPICalls.js
  src/components/sidebar/Sidebar.js
  src/components/sidebar/reviews/MyReviewsPopover.js
  src/css/components/Sidebar.css
  src/css/reviews/MyReviewsPopover.module.css
  src/module/ReviewModule.js
  src/pages/Login.js
Labels: merge

#111 [FIX] 리뷰 재연동
  src/api/ReviewAPICalls.js
  src/components/perfumes/BookmarkPopover.js
  src/components/perfumes/PerfumeDetail.js
  src/components/perfumes/PerfumeReviewState.js
  src/components/perfumes/PerfumeReviews.js
  src/components/perfumes/ReviewSlider.js
  src/components/perfumes/SimilarPerfumes.js
  src/css/perfumes/PerfumeReviews.module.css
  src/module/PerfumeModule.js
  src/module/ReviewModule.js
Labels: merge

#116 [FEAT] 센트렌즈 기능 연동
  package-lock.json
  package.json
  src/App.js
  src/css/Main.css
  src/css/ScentLens.css
  src/css/image/ReactCrop.css
  src/pages/Main.js
  src/pages/Scentlens.js
  src/pages/ThemeEffect.js
  src/pages/image/ImageCropper.js
  src/pages/image/ImageRotator.js
  src/pages/scentlens/PerfumeCard.js
  src/pages/scentlens/PerfumeCarousel.js
Labels: merge

#117 Fix/chat link
  package-lock.json
  package.json
  src/App.js
  src/api/ChatAPICalls.js
  src/api/HistoryAPICalls.js
  src/components/chat/input/ChatInput.js
  src/components/chat/input/ImageUpload.js
  src/components/chat/layout/ChatContainer.js
  src/components/chat/messages/GuideMessages.js
  src/components/chat/messages/MessageItem.js
  src/components/chat/messages/MessageList.js
  src/components/chat/messages/RecommendationItem.js
  src/components/chat/messages/SaveScentButton.js
  src/components/chat/modals/ImageModal.js
  src/components/chat/modals/LoginModal.js
  src/components/perfumes/PerfumeReviewState.js
  src/components/perfumes/PerfumeReviews.js
  src/components/perfumes/ReviewSlider.js
  src/css/History.css
  src/css/Main.css
  src/css/chat/ChatContainer.module.css
  src/css/chat/ChatInput.module.css
  src/css/chat/GuideMessages.module.css
  src/css/chat/MessageItem.module.css
  src/css/chat/MessageList.module.css
  src/css/chat/Modal.module.css
  src/css/chat/RecommendationItem.module.css
  src/css/chat/SaveScentButton.module.css
  src/css/perfumes/PerfumeDetail.module.css
  src/css/perfumes/PerfumeReviews.module.css
  src/css/perfumes/SimilarPerfumes.module.css
  src/css/scentlens/PerfumeCard.module.css
  src/css/scentlens/PerfumeCarousel.module.css
  src/css/scentlens/Scentlens.module.css
  src/module/ChatModule.js
  src/pages/Main.js
  src/pages/chat/hooks/useAuth.js
  src/pages/chat/hooks/useChat.js
  src/pages/chat/hooks/useChatHistory.js
  src/pages/chat/hooks/useMessages.js
  src/pages/chat/hooks/useModal.js
  src/pages/chat/hooks/useRecommendation.js
  src/pages/history/History.js
  src/pages/scentlens/PerfumeCard.js
  src/pages/scentlens/Scentlens.js
  src/pages/scentlens/hooks/ThemeEffect.js
  src/pages/scentlens/image/ImageCropper.js
  src/pages/scentlens/image/ImageRotator.js
  src/pages/scentlens/perfumeCard/PerfumeCard.js
  src/pages/scentlens/perfumeCard/PerfumeCarousel.js
Labels: merge

#119 Fix/guide fix
  src/components/chat/messages/GuideMessages.js
  src/components/chat/messages/RecommendationItem.js
  src/css/chat/GuideMessages.module.css
  src/css/chat/RecommendationItem.module.css
Labels: merge

#121 [FIX] 채팅에서 디퓨저 추천에 none으로 나오는거 수정
  src/components/chat/messages/RecommendationItem.js
Labels: merge
